version: 2
updates:
  - package-ecosystem: "pip"
    directory: "{{cookiecutter.repo_name}}/"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: chore
  - package-ecosystem: "npm"
    directory: "{{cookiecutter.repo_name}}/"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: chore
