# unless otherwise specified, hooks run on push only
default_stages: [pre-push]
repos:
  - repo: https://github.com/crate-ci/typos
    rev: v1.23.2
    hooks:
      - id: typos
  - repo: https://github.com/ComPWA/taplo-pre-commit
    rev: v0.9.3
    hooks:
      - id: taplo-format
  - repo: local
    hooks:
      - id: snapshots
        name: snapshots
        entry: make snapshots
        # run on all files
        pass_filenames: false
        language: system
  - repo: local
    hooks:
      - id: format
        name: format
        language: system
        files: \.(md|yaml|yml|json)$
        entry: npx prettier --write
