# unless otherwise specified, hooks run on push only
default_stages: [push]
repos:
  # disabled because {{cookiecutter.repo_name}}/pyproject.toml is jinja not valid toml
  # - repo: https://github.com/crate-ci/typos
  #   rev: v1.23.2
  #   hooks:
  #     - id: typos
  # formatters and linters are available in the virtualenv so they can be run from the makefile & vscode
  - repo: local
    hooks:
      - id: snapshots
        name: snapshots
        entry: make snapshots
        # run on all files
        pass_filenames: false
        language: system
