name: CI

on:
  push:
    branches: [main]
  pull_request_target:
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      id: setup-python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
    - name: Test
      run: make -B test
