name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      id: setup-python
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Cache virtualenv
      id: cache-venv
      uses: actions/cache@v2
      with:
        path: .venv
        key: ${{ runner.os }}-py${{ steps.setup-python.outputs.python-version }}-venv-${{ hashFiles('setup.py') }}
    - name: make test
      run: make test
