name: Snapshot

on:
  push:
    branches: [main]
  pull_request_target:

permissions:
  contents: write
  actions: write

jobs:
  snapshot:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      id: setup-python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
    - name: Configure Git
      run: |
        git config user.name "$GITHUB_ACTOR"
        git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
    - name: Snapshot
      run: make -B snapshot
    - name: Commit and push any changes
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        git add .
        if git commit -m "chore: update snapshot"; then
          git push
          # git push won't trigger workflows so we manually do it
          # see https://github.com/orgs/community/discussions/25702#discussioncomment-8650283
          gh workflow run ci.yml
        fi
